format = """
$all\
$fill\
$c\
$cmake\
$nodejs\
$python\
$time\
$line_break\
$character"""

add_newline = false

[character]
#error_symbol = '[✗](bold red) '

[c]
format = '[$symbol($version(-$name) )]($style)'

[cmake]
format = ' [$symbol($version )]($style)'

[conda]
format = ' [$symbol$environment]($style) '
ignore_base = false
style = 'white'

[directory]
style = 'bold blue'

[fill]
symbol = ' '

[jobs]
symbol = '⚙'
style = 'bold purple'

[python]
format = ' [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[time]
disabled = false
format =' [$time]($style) ' 
style = 'bright-black'
