"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Inspired_by::
"   https://github.com/amix/vimrc
"
" Sections:
"   -> General
"   -> Plugins
"   -> VIM user interface
"   -> Colors and Fonts
"   -> Files and backups
"   -> Text, tab and indent related
"   -> Visual mode related
"   -> Moving around, tabs and buffers
"   -> Editing mappings
"   -> Spell checking
"   -> Misc
"   -> Helper functions
"
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => General
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" automatic reloading of .vimrc
autocmd! BufWritePost .vimrc source %

" Sets how many lines of history VIM has to remember
set history=700

" Enable filetype plugins
" see file specific configurations in $HOME/.vim/ftplugin
filetype plugin on
filetype indent on

" register terminal key codes here in order to use them in mappings
if !has('gui_running')
    if &term =~ 'alacritty\|xterm'
        set <S-F3>=[1;2R
        set <M-j>=j
        set <M-k>=k
        set <M-l>=l
        set <M-h>=h
        map <C-@> <C-Space>
        map! <C-@> <C-Space>
    endif
endif

" Set to auto read when a file is changed from the outside
" | execute 'redraw!'
set autoread
if !has("gui_running")
    augroup autoread
        autocmd!
        autocmd FocusGained * : silent! checktime
        autocmd WinEnter,BufEnter,BufWinEnter * :silent! checktime
        autocmd CursorMoved,CursorMovedI * :silent! checktime
        " Disable if performance hit becomes noticable
        autocmd CursorHold,CursorHoldI * :silent! checktime
    augroup END
endif

" Return to last edit position when opening files
augroup lastedit
    autocmd!
    autocmd BufReadPost *
        \ if line("'\"") > 0 && line("'\"") <= line("$") |
        \   exe "normal! g`\"" |
        \ endif
augroup END

" NOTE: the usual way of setting the <Leader>:
"   let mapleader = "\<Space>"
" requires an additional mapping to prevent timeouts from triggering <Right>:
"   nnoremap <Space> <Nop>
" causing its own problems as the timedout sequence is trapped, see:
" https://vi.stackexchange.com/questions/13862/using-a-no-op-key-in-insert-mode-cant-use-key-after-using-no-op-mapping
" Mapping the desired key to <Leader> directly instead has the additional
" advantage of echoing when `showcmd` is set.
map <Space> <Leader>
let maplocalleader = "<Leader>"

" better copy & paste
set clipboard=unnamed,unnamedplus
set pastetoggle=<F8>

" OPTIONAL: Starting with Vim 7, the filetype of empty .tex files defaults to
" 'plaintex' instead of 'tex', which results in vim-latex not being loaded.
" The following changes the default filetype back to 'tex':
let g:tex_flavor='latex'

" Start netrw with dotfiles hidden
let g:netrw_list_hide = '\(^\|\s\s\)\zs\.\S\+'

" Disable interpretation of numbers with leading 0 as octal when using <C-A>/<C-X>
set nrformats-=octal

" Delete comment character when joining commented lines
set formatoptions+=j

" Move viminfo file to ~/.vim directory to prevent clutter in $HOME
set viminfofile=~/.vim/viminfo

" Remember global variables consisting of capital letters (e.g. 'KEEP_THIS')
set viminfo^=!

" Disable Ex-mode
nnoremap Q <Nop>

" search for tags in current directory and all parents (until root)
if has('path_extra')
    setglobal tags=./tags;~
endif

" use tjump to select tags if there is more than one match
noremap <C-]> g<C-]>
noremap g<C-]> <C-]>

" time to wait for completing mappings / terminal keycodes [ms]
" NOTE: as keycodes aren't typed manually, low timeouts prevent blocking <Esc>
set timeoutlen=750 ttimeoutlen=25

" vim 8 introduced a mode to discern between keys like <Tab> and <C-I> if the
" terminal supports it (e.g. xterm). This however causes problems in
" gnome-terminal, therefore this will be disabled (see `:h modifyOtherKeys`)
if v:version >= 800
    let &t_TI = ""
    let &t_TE = ""
endif

set diffopt+=vertical
if has("patch-8.1.0360")
    set diffopt+=algorithm:histogram,indent-heuristic
endif

" Disable macro recording when insinde cmdline-window (`q:`, `q/`, `q?`)
" and press 'q' to close the window
augroup cmdlinewindow
    autocmd!
    autocmd CmdwinEnter * noremap <buffer> <silent> <nowait> q <Cmd>quit<CR>
augroup END

" The swap file as well as a lot of other stuff depends on `updatetime`.
" We do not use swap, but gitgutter and tagbar are more pleasant with this.
set updatetime=100


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Plugins
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" matchit: enhanced %-key matching, ships with vim {{{
packadd! matchit
" }}}

" termdebug: gdb integration, ships with vim {{{
packadd! termdebug
let g:termdebug_config = #{
                         \ wide: 1,
                         \ disasm_window: v:false,
                         \ variables_window: v:false,
                         \}
nnoremap <Leader>db <Cmd>Break<CR>
nnoremap <Leader>dB <Cmd>Clear<CR>
nnoremap <Leader>dj <Cmd>Over<CR>
nnoremap <Leader>dJ <Cmd>Continue<CR>
nnoremap <Leader>dl <Cmd>Step<CR>
" }}}

" cfilteR: quickfix list filter plugin, ships with vim {{{
packadd! cfilter
" }}}

" man: man pager, ships with vim {{{
runtime ftplugin/man.vim
let g:ft_man_open_mode = 'vert'
set keywordprg=:Man
" }}}

" automatically update the gnu-global database, see `~/.vim/plugin/gtags.vim`
" Note: should be managed by gutentags for now
"let g:Gtags_Auto_Update = 1
noremap <Leader>c] <Cmd>GtagsCursor<CR>
"set cscopetag

" Make sure that vim-plug is installed, see:
" https://github.com/junegunn/vim-plug/wiki/tutorial
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Plugins will be downloaded under the specified directory.
" Make sure you use single quotes
call plug#begin('~/.vim/plugged')

    " Appearance
    " vim-airline: better statusbar + themes {{{
    Plug 'vim-airline/vim-airline'
    Plug 'vim-airline/vim-airline-themes'
    " Disable default option to show current mode, as airline will do this for us
    augroup airline_showmode
        autocmd!
        autocmd User AirlineToggledOn set noshowmode
        autocmd User AirlineToggledOff set showmode
    augroup END
    " Display buffers in the tab line if only one tab is open
    let g:airline#extensions#tabline#enabled = 1
    " Show only filename in tabline
    let g:airline#extensions#tabline#formatter = 'unique_tail'
    " unicode symbols
    if !exists('g:airline_symbols')
        let g:airline_symbols = {}
    endif
    let g:airline_symbols.crypt = '🔒'
    let g:airline_symbols.branch = 'ᚠ'
    let g:airline_symbols.spell = 'Ⓢ'
    let g:airline_symbols.notexists = 'Ɇ'
    let g:airline_symbols.linenr = ' '
    let g:airline_symbols.maxlinenr = ''
    let g:airline_symbols.colnr = ':'
    let g:airline#extensions#obsession#indicator_text = 'Ⓞ'
    " }}}
    " collection of color schemes {{{
    Plug 'rafi/awesome-vim-colorschemes'
    Plug 'vim-scripts/peaksea'
    Plug 'skielbasa/vim-material-monokai'
    " }}}
    " undotree: visualization of undo history {{{
    Plug 'mbbill/undotree'
    let g:undotree_WindowLayout = 4
    nnoremap <Leader>u <Cmd>UndotreeToggle<CR>
    " }}}
    " tagbar: tagbrowser, useful for C++ classes {{{
    Plug 'preservim/tagbar'
    noremap [ot <Cmd>TagbarOpen<CR>
    noremap ]ot <Cmd>TagbarClose<CR>
    noremap yot <Cmd>TagbarToggle<CR>
    " }}}
    " vim-highlightedyank: highlight the yanked text {{{
    Plug 'machakann/vim-highlightedyank'
    let g:highlightedyank_max_lines = 250
    let g:highlightedyank_highlight_duration = 500
    " }}}
    " editorconfig: keep editor settings in sync via `.editorconfig` {{{
    Plug 'editorconfig/editorconfig-vim'
    " Disable for fugutive and terminal windows
    let g:EditorConfig_exclude_patterns = ['fugitive://.*', '^.*!\w*sh$']
    " }}}
    " vim-obsession: better session management {{{
    Plug 'tpope/vim-obsession'
    " }}}
    " auto-pairs: Automatically pair all styles of braces and quotes {{{
    Plug 'lunarWatcher/auto-pairs'
    let g:AutoPairsShortcutFastWrap = '<C-p><C-f>'
    let g:AutoPairsMapBS = 1
    " }}}
    " plantuml-syntax: highlighting {{{
    Plug 'aklt/plantuml-syntax'
    " }}}
    "vim-cpp-modern: Enhanced syntax highlighting for C and C++ {{{
    Plug 'bfrg/vim-cpp-modern'
    "}}}
    " Frameworks
    " vim-latex: latex IDE for vim {{{
    Plug 'vim-latex/vim-latex'
    " set grep program to always generate a file-name, even for single match
    if executable('rg')
        let &grepprg = 'rg --vimgrep $*'
        set grepformat=%f:%l:%c:%m
    else
        set grepprg=grep\ -nH\ $*
    endif
    " }}}
    " Functionality
    " vim-repeat: make repeat command '.' work with plugins {{{
    Plug 'tpope/vim-repeat'
    " }}}
    " vim-surrround: better manipulation of brackets and HTML/XML tags {{{
    Plug 'tpope/vim-surround'
    " }}}
    " vim-commentary: add 'gc' command for commenting {{{
    Plug 'tpope/vim-commentary'
    " }}}
    " vim-eunuch: Add common UNIX shell commands {{{
    Plug 'tpope/vim-eunuch'
    " }}}
    " vim-unimpaired: pairs of useful mappings {{{
    Plug 'tpope/vim-unimpaired'
    nnoremap <silent> yoq <Cmd>silent ToggleQuickFix<CR>
    nnoremap <silent> [oq <Cmd>cclose<CR>
    nnoremap <silent> ]oq <Cmd>copen<CR>
    nnoremap <silent> =sq <Cmd>silent ToggleQuickFix<CR>
    nnoremap <silent> <sq <Cmd>cclose<CR>
    nnoremap <silent> >sq <Cmd>copen<CR>
    " }}}
    " vim-exchange: exchange command `cx` {{{
    Plug 'tommcdo/vim-exchange'
    " }}}
    " vim-easy-align: align text objects, useful for tables, etc. {{{
    Plug 'junegunn/vim-easy-align'
    nmap ga <Plug>(EasyAlign)
    xmap ga <Plug>(EasyAlign)
    " }}}
    " vim-vinegar: enhance netrw behaviour {{{
    Plug 'tpope/vim-vinegar'
    " }}}
    " vim-dirvish: file explorer {{{
    Plug 'justinmk/vim-dirvish'
    Plug 'kristijanhusak/vim-dirvish-git'
    let g:dirvish_git_indicators = {
    \ 'Modified'  : '✹',
    \ 'Staged'    : '✚',
    \ 'Untracked' : '✭',
    \ 'Renamed'   : '➜',
    \ 'Unmerged'  : '═',
    \ 'Ignored'   : '☒',
    \ 'Unknown'   : '?'
    \ }
    " Group directories first
    let g:dirvish_mode = ':sort ,^.*[\/],'
    " }}}
    " vim-indent-object: new text object based on indentation level {{{
    Plug 'michaeljsmith/vim-indent-object'
    " }}}
    " targets: Additional textobjects to operate on {{{
    Plug 'wellle/targets.vim'
    " }}}
    " quick-scope: highlight targets of next f/F/t/T find command {{{
    Plug 'unblevable/quick-scope'
    let g:qs_highlight_on_keys = ['f', 'F', 't', 'T']
    " }}}
    " vim-sneak: better version of f/F builtin commands {{{
    Plug 'justinmk/vim-sneak'
    let g:sneak#label = 1
    " }}}

    " " markdown folding, concealing and syntax highlight
    " Plug 'plasticboy/vim-markdown'
    " let g:vim_markdown_conceal_code_blocks = 0
    " let g:vim_markdown_new_list_item_indent = 0
    " let g:vim_markdown_folding_style_pythonic = 1
    " let g:vim_markdown_no_extensions_in_markdown = 1

    " Note Taking
    " vimwiki: manage notes, todo lists, etc. {{{
    Plug 'vimwiki/vimwiki', {'branch': 'dev'}
    let g:vimwiki_global_ext = 0
    let g:vimwiki_auto_chdir = 1
    let g:vimwiki_list = [{ 'path': '~/Documents/vimwiki/',
                           \'syntax': 'markdown',
                           \'ext': '.md',
                           \'links_space_char': '_',
                           \'auto_header': 1,
                           \'auto_toc': 1,
                           \'auto_tags': 1,
                           \'auto_diary_index': 1,
                        \}]
    " Fix standard mappings not recognizing second leader
    nmap <Leader>w<Space>w <Plug>VimwikiMakeDiaryNote
    nmap <Leader>w<Space>t <Plug>VimwikiTabMakeDiaryNote
    nmap <Leader>w<Space>y <Plug>VimwikiMakeYesterdayDiaryNote
    nmap <Leader>w<Space>m <Plug>VimwikiMakeTomorrowDiaryNote
    " }}}
    " calendar-vim: calendar, particularly useful for vimwiki {{{
    Plug 'mattn/calendar-vim'
    let g:vimwiki_use_calendar = 1
    let g:calendar_monday = 1
    let g:calendar_no_mappings = 0
    let g:calendar_mark = 'right'
    " }}}
    " Programming
    " ALE: asynchronous linting engine {{{
    Plug 'dense-analysis/ale'
    " Disable for markdown to avoid local list conflict with vimwiki
    let g:ale_pattern_options = {'\.md$': {'ale_enabled': 0}}
    " Use a balloon-like floating instead of a separate preview-window
    let g:ale_floating_preview = 1
    let g:ale_floating_window_border = ['│', '─', '╭', '╮', '╯', '╰', '│', '─']
    " Use balloons to present errors and hover info (currently only in gvim)
    let g:ale_set_balloons = 1
    " Disable printing hover info to echo line 
    let g:ale_hover_cursor = 0
    " ALE mappings
    nmap <silent> [W         <Plug>(ale_first)
    nmap <silent> [w         <Plug>(ale_previous)
    nmap <silent> ]w         <Plug>(ale_next)
    nmap <silent> ]W         <Plug>(ale_last)
    nmap <silent> yoa        <Plug>(ale_toggle)
    nmap <silent> ]oa        <Plug>(ale_enable)
    nmap <silent> [oa        <Plug>(ale_disable)
    nmap <silent> <Leader>ad <Plug>(ale_detail)
    nmap <silent> <Leader>af <Plug>(ale_fix)
    " }}}
    " LSP {{{
    let g:ale_disable_lsp = 1
    Plug 'yegappan/lsp'
    let lspOpts = #{
                \   autoHighlightDiags: v:true,
                \   completionMatcher: 'icase',
                \   noNewLineInCompletion: v:true,
                \   diagVirtualTextAlign: "after",
                \   showDiagWithVirtualText: v:true,
                \   semanticHighlight: v:true,
                \ }
    autocmd User LspSetup call LspOptionsSet(lspOpts)
    let lspServers = [
                \     #{
                \       name: 'clangd',
                \       filetype: ['c', 'cpp'],
                \       path: '/usr/bin/clangd',
                \       args: ['--background-index', '--clang-tidy'],
                \     },
                \     #{
                \       name: 'pylsp',
                \       filetype: 'python',
                \       path: exepath('pylsp'),
                \       args: [],
                \     },
                \     #{
                \       name: 'rust-analyzer',
                \       filetype: 'rust',
                \       path: exepath('rust-analyzer'),
                \       args: [],
                \       syncInit: v:true,
                \     },
                \]
    autocmd User LspSetup call LspAddServer(lspServers)
    augroup LSPMappings
        autocmd!
        autocmd User LspAttached call LSPMappings()
    augroup END
    " }}}
    " vim-gutentags: automatic tag generation and management {{{
    Plug 'ludovicchabant/vim-gutentags'
    Plug 'skywind3000/gutentags_plus'
    let g:gutentags_exclude_project_root = ['/usr/local', expand('~/.dotfiles'), expand('~/.vim')]
    let g:gutentags_modules = ['ctags', 'gtags_cscope']
    let g:gutentags_project_root = ['.root']
    let g:gutentags_file_list_command = {
        \ 'markers': {
            \ '.git': 'git ls-files',
            \ '.hg': 'hg files',
            \ },
        \ }
    " The following maps are introduced by gutentags_plus
    " | keymap       | desc                                             |
    " | --------     | ------                                           |
    " | `<leader>cs` | Find symbol (reference) under cursor             |
    " | `<leader>cg` | Find symbol definition under cursor              |
    " | `<leader>cd` | Functions called by this function                |
    " | `<leader>cc` | Functions calling this function                  |
    " | `<leader>ct` | Find text string under cursor                    |
    " | `<leader>ce` | Find egrep pattern under cursor                  |
    " | `<leader>cf` | Find file name under cursor                      |
    " | `<leader>ci` | Find files #including the file name under cursor |
    " | `<leader>ca` | Find places where current symbol is assigned     |
    " | `<leader>cz` | Find current word in ctags database              |
    " }}}
    " Snippets {{{
    Plug 'sirver/ultisnips'
    Plug 'honza/vim-snippets'
    let g:UltiSnipsExpandTrigger = "<Tab>"
    let g:snips_author = "Florian Prawits"
    let g:snips_email = "florian.prawits@ait.ac.at"
    let g:snips_github = "https://git-service.ait.ac.at/prawitsf"
    " }}}
    " git-integration: vim-fugitive, gv, fugitive-gitlab, gitgutter, conflict-marker {{{
    Plug 'tpope/vim-fugitive'
    nnoremap <Leader>gb <Cmd>Git blame<CR>
    nnoremap <Leader>gs <Cmd>Git<CR>
    nnoremap <Leader>gg :Ggrep --quiet <C-R><C-W><CR>
    Plug 'junegunn/gv.vim'
    nnoremap <Leader>gv <Cmd>GV<CR>
    nnoremap <Leader>gV <Cmd>GV!<CR>
    Plug 'shumphrey/fugitive-gitlab.vim'
    let g:fugitive_gitlab_domains = [ 'https://git-service.ait.ac.at' ]
    let g:gitlab_api_keys = {'git-service.ait.ac.at': ''}
    nnoremap <Leader>gx <Cmd>GBrowse<CR>
    Plug 'airblade/vim-gitgutter'
    Plug 'rhysd/conflict-marker.vim'

    " }}}
    " Tools
    " fzf integration (fuzzy finder) {{{
    Plug 'junegunn/fzf', { 'do': './install --all' }
    Plug 'junegunn/fzf.vim'
    nnoremap <Leader>fb   <Cmd>Buffers<CR>
    nnoremap <Leader>ff   <Cmd>Files<CR>
    nnoremap <Leader>fl   <Cmd>Lines<CR>
    nnoremap <Leader>fL   <Cmd>BLines<CR>
    nnoremap <Leader><F1> <Cmd>Helptags<CR>
    nnoremap <Leader>fr   :Rg<Space><C-R><C-W><CR>
    vnoremap <Leader>fr   "zy:Rg<Space><C-R>z<CR>
    nnoremap <Leader>fR   :Rg<Space>
    nnoremap <Leader>fw   <Cmd>Windows<CR>
    nnoremap <Leader>fg   :Locate<Space>
    nnoremap <Leader>ft   <Cmd>Tags<CR>
    nnoremap <Leader>fT   <Cmd>BTags<CR>
    nnoremap <Leader>fm   <Cmd>Marks<CR>
    nnoremap <Leader>fh   <Cmd>History<CR>
    nnoremap <Leader>f:   <Cmd>History:<CR>
    nnoremap <Leader>f/   <Cmd>History/<CR>
    nnoremap <Leader>fc   <Cmd>Commands<CR>
    nnoremap <Leader>fs   <Cmd>Snippets<CR>
    nnoremap <Leader>gf   <Cmd>GFiles<CR>
    nnoremap <Leader>gF   <Cmd>GFiles?<CR>
    nnoremap <Leader>gc   <Cmd>Commits<CR>
    nnoremap <Leader>gC   <Cmd>BCommits<CR>
    nmap <leader><tab> <plug>(fzf-maps-n)
    xmap <leader><tab> <plug>(fzf-maps-x)
    omap <leader><tab> <plug>(fzf-maps-o)
    imap <C-K> <plug>(fzf-complete-word)
    imap <C-F> <plug>(fzf-complete-path)
    imap <C-L> <plug>(fzf-complete-line)
    " Customize fzf colors to match color scheme
    let g:fzf_colors =
    \ { 'fg':      ['fg', 'Normal'],
      \ 'bg':      ['bg', 'Normal'],
      \ 'hl':      ['fg', 'Comment'],
      \ 'fg+':     ['fg', 'CursorLine', 'CursorColumn', 'Normal'],
      \ 'bg+':     ['bg', 'CursorLine', 'CursorColumn'],
      \ 'hl+':     ['fg', 'Statement'],
      \ 'info':    ['fg', 'PreProc'],
      \ 'border':  ['fg', 'Ignore'],
      \ 'prompt':  ['fg', 'Conditional'],
      \ 'pointer': ['fg', 'Exception'],
      \ 'marker':  ['fg', 'Keyword'],
      \ 'spinner': ['fg', 'Label'],
      \ 'header':  ['fg', 'Comment'] }
    " Helper function for fzf populate qf-list binding
    function! s:build_quickfix_list(lines)
        call setqflist(map(copy(a:lines), '{ "filename": v:val }'))
        copen
        cc
    endfunction
    " An action can be a reference to a function that processes selected lines
    let g:fzf_action = {
      \ 'ctrl-q': function('s:build_quickfix_list'),
      \ 'ctrl-t': 'tab split',
      \ 'ctrl-x': 'split',
      \ 'ctrl-v': 'vsplit' }
    " }}}
    " vim-dirdiff: recursively diff directories {{{
    Plug 'will133/vim-dirdiff'
    " }}}
    " quickfix-reflector: edits in the quickfix window are saved to files {{{
    Plug 'stefandtw/quickfix-reflector.vim'
    " }}}
" List ends here. Plugins become visible to Vim after this call.
call plug#end()


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => VIM user interface
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Better scrolling, high scrolloff keeps cursor centered
set scrolloff=999
set sidescroll=1
set sidescrolloff=5

" Insert completion menu settings
set completeopt=menuone,popup,noinsert,noselect

" Ignore include files as it causes long complete times
set complete-=i

" Turn on the wild menu
set wildmenu
set wildmode=longest:full,full

" Ignore compiled files
set wildignore=*.o,*~,*.pyc
if has("win16") || has("win32")
    set wildignore+=.git\*,.hg\*,.svn\*
else
    set wildignore+=*/.git/*,*/.hg/*,*/.svn/*,*/.DS_Store
endif

" when populating wildmenus, exclude files with these suffixes
set suffixes+=.pdf,.png,.jpg

" Always show current position - obsolete with airline
set ruler

" Change cursor depending on current mode, works for VTE compatible terminals
" taken from: https://vim.fandom.com/wiki/Change_cursor_shape_in_different_modes
if &term =~ 'xterm'
    " let &t_SI = "\<Esc>[5 q"
    let &t_SR = "\<Esc>[4 q"
    let &t_EI = "\<Esc>[2 q"
endif

" Toggle cursorline depending on normal/insert mode
augroup toggle_cursorline
    autocmd!
    autocmd InsertEnter * set nocursorline
    autocmd InsertLeave * set cursorline
augroup END

" show line numbers
set number relativenumber cursorline colorcolumn=80

" Highlight active window with rel. line numbers, cursorline and colorcolumn
augroup highlight_active_window
    autocmd!
    autocmd VimEnter,WinEnter * call HighlightActiveWindow()
    autocmd WinLeave * setlocal nocursorline norelativenumber colorcolumn=
augroup END

" Always show the status line
set laststatus=2

" Height of the command bar
set cmdheight=2

" Show typed commands, useful for showing incomplete sequences of mappings
set showcmd

" Show the number of matches when searching
set shortmess-=S

" A buffer becomes hidden when it is abandoned
set hidden

" Configure backspace so it acts as it should act
set backspace=eol,start,indent
set whichwrap+=<,>,h,l

" In many terminal emulators the mouse works just fine, thus enable it.
if has('mouse')
  set mouse=a
endif

" Ignore case when searching
set ignorecase

" Case sensitive search when the search pattern contains upper case
set smartcase

" Highlight search results
set hlsearch

" Makes search act like search in modern browsers
set incsearch

" Show matching brackets when text indicator is over them
set showmatch
" How many tenths of a second to blink when matching brackets
set matchtime=2

" No annoying sound on errors
set noerrorbells
set novisualbell
set t_vb=

" Add a bit extra margin to the left
set foldcolumn=1

" show whitespace
set list
set listchars=tab:▸\ ,eol:¬,trail:•,extends:»,precedes:«,nbsp:␣

let &showbreak = '↪ '   " highlight wrapped lines
set nowrap              " dont wrap lines
set display+=lastline   " show as much of the last (wrapped) line as possible

" More natural placement of new windows
" set splitbelow splitright

nnoremap <Leader>t <Cmd>terminal<CR>
nnoremap <F10> <Cmd>ToggleQuickFix<CR>
nnoremap <F9> <Cmd>ToggleLocation<CR>

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Colors and Fonts
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Enable syntax highlighting
syntax enable

set background=dark
set termguicolors

try
    let g:gruvbox_italic = '1'
    if !has("gui_running")
        let g:gruvbox_guisp_fallback = 'bg'
    endif
    colorscheme gruvbox
    " correct coloring for terminal inside vim when using guicolors, based on:
    " https://vi.stackexchange.com/questions/25456/how-can-i-change-the-colorscheme-of-the-vim-terminal-buffer
    let g:terminal_ansi_colors = [
        \'#282828', '#CC241D', '#98971A', '#D79921',
        \'#458588', '#B16286', '#689D6A', '#D65D0E',
        \'#fb4934', '#b8bb26', '#fabd2f', '#83a598',
        \'#d3869b', '#8ec07c', '#fe8019', '#FBF1C7' ]
    highlight Terminal guibg='#282828' guifg='#ebdbb2'
catch
endtry

" Enable syntax highlighting in fenced markdown code blocks
let g:markdown_fenced_languages = ['html', 'python', 'bash=sh', 'c', 'cpp']

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Files, backups and undo
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Set utf8 as standard encoding and en_US as the standard language
set encoding=utf-8

" Use Unix as the standard file type
set ffs=unix,dos,mac

" Turn off backup and swap files, use persistent undo instead
set nobackup
set nowb
set noswapfile

if has("persistent_undo")
   let s:target_path = expand('~/.vim/undodir')

    " create the directory and any parent directories
    " if the location does not exist.
    if !isdirectory(s:target_path)
        call mkdir(s:target_path, "p", 0700)
    endif

    let &undodir = s:target_path . '//'
    set undofile
endif

" variable assignment no longer blocks <C-X><C-F> filename completion
set isfname-==

" expand `%%` to the 'head' path of current file, useful for quickly opening
" files in same directory without the need to change cwd - try ':e %%'
cnoremap <expr> %% getcmdtype()==':' ? expand('%:h') . '/' : '%%'

" abbreviations for often used file patterns
" TODO: maybe replace by abbrev or use filetype specific mappings mapped to common key, e.g. <F9>
cnoremap <expr> %c getcmdtype()==':' ? '**/*.[ch]' : '%c'
cnoremap <expr> %py getcmdtype()==':' ? '**/*.py' : '%py'
cnoremap <expr> %md getcmdtype()==':' ? '**/*.md' : '%md'

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Text, tab and indent related
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Use spaces instead of tabs
set expandtab

" Respect shiftwidth setting when using <Tab> in front of a line
set smarttab

" 1 tab == 4 spaces
" softtabstop additionally added in order to no have to delete tab generated
" whitespace individually, see (negative value uses shiftwidth):
" https://stackoverflow.com/questions/1562336/tab-vs-space-preferences-in-vim?rq=1
set tabstop=4
let &shiftwidth = &tabstop
set softtabstop=-1
set shiftround

" Linebreak on 500 characters
set linebreak
set textwidth=500

set autoindent
set smartindent


""""""""""""""""""""""""""""""
" => Visual mode related
""""""""""""""""""""""""""""""
" Visual mode pressing * or # searches for the current selection
" Super useful! From an idea by Michael Naumann
vnoremap <silent> * <Cmd>call VisualSelection('f', '')<CR>
vnoremap <silent> # <Cmd>call VisualSelection('b', '')<CR>

" easier moving of code blocks
" Try to go into visual mode (v), thenselect several lines of code here and
" then press ``>`` several times.
vnoremap < <gv
vnoremap > >gv


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Moving around, tabs, windows and buffers
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Uniform closing
nnoremap <Leader>q <Cmd>q<CR>
nnoremap <Leader>Q <Cmd>qa!<CR>

" Treat long lines as break lines (useful when moving around in them)
noremap j gj
noremap k gk

" Keep cursor centered when searching
nnoremap n nzzzv
nnoremap N Nzzzv

" Easier to enter cmd- and search-mode
" Remark: <C-Space> is send to vim by the terminal as <C-@>
noremap <C-Space> /
" Restrict search to visually selected area
vnoremap <C-Space> <Esc>/\%V
" Use <C-Space> to put word under cursor into commandline
cnoremap <C-Space> <C-R><C-W>

" Redrawing the screen also disables highlight and updates diffs
nnoremap <silent> <C-L> :<C-U>nohlsearch<C-R>=has('diff')?'<Bar>diffupdate':''<CR><CR><C-L>

" Toggle folds
noremap <Leader><Space> za

" With this function we can create cabbreviations that trigger only if:
"   1) commandline is beginning with ':', not '/' or '?'
"   2) only right after the ':', i.e. there is nothing after the cursor
function! CNoreAbbrev(abb, ...)
    "execute 'cnoreabbrev <expr> '.a:abb.' getcmdtype()==":" && getcmdpos()==strlen('.string(a:abb).')+1 && getcmdline()=='.string(a:abb).' ? '.string(a:exp).' : '.string(a:abb)
     execute 'cnoreabbrev <expr> '.a:abb.' getcmdtype()==":" && getcmdline()=='.string(a:abb).' ? '.string(join(a:000)).' : '.string(a:abb)
endfunction
command! -nargs=+ CNoreAbbrev call CNoreAbbrev(<f-args>)

" show bufferlist when switching/deleting/splitting buffers
CNoreAbbrev b buffers<CR>:buffer
CNoreAbbrev bd buffers<CR>:bdelete
CNoreAbbrev bdel buffers<CR>:bdelete
CNoreAbbrev sb buffers<CR>:sb
CNoreAbbrev vsb buffers<CR>:vertical sb

" Close all buffers except for the current one
nnoremap <Leader>bo <Cmd>%bdelete<Bar>edit #<Bar>bdelete #<Bar>normal g`"<CR>

" Quick switch between current and alternate buffer
nnoremap <Backspace> <C-^>

" open help in vertical split
CNoreAbbrev h vert h

" map <F3> and <S-F3> to jump between locations in a quickfix list, or
" differences if in window in diff mode
nnoremap <expr> <silent> <F3>   (&diff ? "]c" : ":cnext\<CR>")
nnoremap <expr> <silent> <S-F3> (&diff ? "[c" : ":cprev\<CR>")

" Creating and resizing split windows
nnoremap <silent> <Leader>s <C-W><C-S>
nnoremap <silent> <Leader>v <C-W><C-V>
nnoremap <Leader>= <C-W>=

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Editing mappings
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Press jj to enter command mode
inoremap jj <ESC>

" Make Y consistent with other cmds in capital form
noremap Y y$

" Easier typing of go to mark command
noremap gm `
noremap gM '

" Insert undo breaks
inoremap <C-U> <C-G>u<C-U>
inoremap <C-W> <C-G>u<C-W>
inoremap , ,<C-G>u
inoremap . .<C-G>u
inoremap ! !<C-G>u
inoremap ? ?<C-G>u

" Bash like cmdline editing mappings for moving around
cnoremap <C-A> <Home>
cnoremap <C-F> <Right>
cnoremap <C-B> <Left>
cnoremap <Esc>b <S-Left>
cnoremap <Esc>f <S-Right>

" show registers
" taken from http://superuser.com/questions/656949/always-show-the-register-list-in-vim
nnoremap <silent> "" <Cmd>registers "0123456789abcdefghijklmnopqrstuvwxyz*+.<CR>

" Delete trailing white space on save
func! DeleteTrailingWS()
  let l:winview = winsaveview()
  keeppatterns %s/\s\+$//e
  call winrestview(l:winview)
endfunc
augroup trailingws
    autocmd!
    autocmd BufWritePre *.c,*.h :call DeleteTrailingWS()
    autocmd BufWritePre *.cpp,.*hpp :call DeleteTrailingWS()
    autocmd BufWritePre *.py :call DeleteTrailingWS()
    autocmd BufWritePre *.coffee :call DeleteTrailingWS()
augroup END

" useful mappings for direct interaction with system clipboard
if has('clipboard')
    nnoremap <expr> <Leader>p &paste ? '"+p' : ':setlocal paste<CR>"+p:setlocal nopaste<CR>'
    xnoremap <expr> <Leader>p &paste ? '"+p' : ':setlocal paste<CR>"+p:setlocal nopaste<CR>'
endif

" When you press <Leader>r you can search and replace the selected text
" vnoremap <silent> <Leader>r :call VisualSelection('replace', '')<CR>

" Use * or # as motion for the change/delete commands, repeat with `.` afterwards
nnoremap c* *``cgn
nnoremap c# #``cgN
nnoremap d* *``dgn
nnoremap d# #``dgN

" Uniform escaping
inoremap <C-Q>     <Esc>
noremap  <C-Q>     <Esc>
cnoremap <C-Q>     <C-C>

" Hitting <CR> during ins-completion will accept current selection, irrespective of state
" Currently shadowed by Eunuch and Autopairs
inoremap <expr> <CR> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"

" Insert completion mappings
inoremap <C-]> <C-x><C-]>
inoremap <C-b> <C-x><C-p>
" The mappings below are currently used by the fzf completion equivalents
" inoremap <C-k> <C-x><C-k>
" inoremap <C-f> <C-x><C-f>
" inoremap <C-l> <C-x><C-l>

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Spell checking
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set dictionary+=spell
if has('unix')
    set dictionary+=/usr/share/dict/words
    set thesaurus+=~/.vim/thesaurus/english.txt
endif

" Turn on spell checking with specific language
" noremap <Leader>se :setlocal spell spelllang=en_us<CR>
" noremap <Leader>sd :setlocal spell spelllang=de_de<CR>

" Shortcuts using <Leader>
" noremap <Leader>sn ]s
" noremap <Leader>sp [s
" noremap <Leader>sa zg
" noremap <Leader>ss z=

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Misc
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Remove the Windows ^M - when the encodings gets messed up
noremap <Leader>m mmHmt:%s/<C-V><CR>//ge<CR>'tzt'm

" Fast saving
noremap <C-S> <Cmd>update<CR>

" :w!! sudo saves the file
" (useful for handling the permission-denied error)
cnoreabbrev w!! w !sudo /usr/bin/tee % > /dev/null

" common typos
command! -bang -nargs=? -complete=file E   e<bang> <args>
command! -bang -nargs=? -complete=file W   w<bang> <args>
command! -bang -nargs=? -complete=file Wq wq<bang> <args>
command! -bang -nargs=? -complete=file WQ wq<bang> <args>
command! -bang Wa wa<bang>
command! -bang WA wa<bang>
command! -bang Q  q<bang>
command! -bang Qa qa<bang>
command! -bang QA qa<bang>

" insert current date and time
inoreabbrev <expr> cdate strftime("%F")
inoreabbrev <expr> xdate strftime("%F %T")
" insert email address
inoreabbrev @@ florian.prawits@ait.ac.at

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Helper functions
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
function! HighlightActiveWindow()
    if &number
        setlocal relativenumber
    endif
    " Do not add the cursorline, if it was explicitly disabled, e.g. from an
    " ftplugin via:
    "   let b:disable_active_window_highlight_cul = 1
    if !get(b:, 'disable_active_window_highlight_cul', 0)
        setlocal cursorline
    endif
    " Do not add the colorcolumn, if it was explicitly disabled, e.g. from an
    " ftplugin via:
    "   let b:disable_active_window_highlight_cc = 1
    if !get(b:, 'disable_active_window_highlight_cc', 0)
        setlocal colorcolumn=80
    endif
endfunction

function! CmdLine(str)
    exe "menu Foo.Bar :" . a:str
    emenu Foo.Bar
    unmenu Foo
endfunction

function! VisualSelection(direction, extra_filter) range
    let l:saved_reg = @"
    execute "normal! vgvy"

    let l:pattern = escape(@", '\\/.*$^~[]')
    let l:pattern = substitute(l:pattern, "\n$", "", "")

    if a:direction == 'b'
        execute "normal ?" . l:pattern . "^M"
    elseif a:direction == 'gv'
        call CmdLine("Ack \"" . l:pattern . "\" " )
    elseif a:direction == 'replace'
        call CmdLine("%s" . '/'. l:pattern . '/')
    elseif a:direction == 'f'
        execute "normal /" . l:pattern . "^M"
    endif

    let @/ = l:pattern
    let @" = l:saved_reg
endfunction

function! ToggleQuickFix()
    if getqflist({'winid': 0}).winid
    " Alternative implementation
    " if !empty(filter(getwininfo(), 'v:val.quickfix'))
        cclose
    else
        copen
    endif
endfunction
command! -nargs=0 -bar ToggleQuickFix silent call ToggleQuickFix()

function! ToggleLocation()
    if getloclist(0, {'winid': 0}).winid
        lclose
    else
        lopen
    endif
endfunction
command! -nargs=0 -bar ToggleLocation silent! call ToggleLocation()

" latex-suite already defines a mapping (<leader>ls) for forward searching.
" Alternatively the following can be used
"function! SyncTexForward()
"    let execstr = "silent !zathura --synctex-forward ".line(".").":".col(".").":%:p %:p:r.pdf &"
"    exec execstr
"endfunction
"noremap <leader>lf :call SyncTexForward()<CR>
"

" Cite as you write integration of Zotero API, taken from
" https://retorque.re/zotero-better-bibtex/citing/cayw/
function! ZoteroCite()
  " pick a format based on the filetype (customize at will)
  let format = &filetype =~ '.*tex' ? 'citep' : 'pandoc'
  let api_call = 'http://127.0.0.1:23119/better-bibtex/cayw?format='.format.'&brackets=1'
  let ref = system('curl -s '.shellescape(api_call))
  return ref
endfunction
noremap <leader>z "=ZoteroCite()<CR>p
inoremap <C-z> <C-r>=ZoteroCite()<CR>

function LSPMappings()
  " imap <buffer> <C-Space> <Plug>(ale_complete)
  nnoremap <buffer> <LocalLeader>k <Cmd>LspHover<CR>
  nnoremap <buffer> gd <Cmd>LspGotoDefinition<CR>
  nnoremap <buffer> gr <Cmd>LspShowReferences<CR>
  nnoremap <buffer> gR <Cmd>LspRename<CR>
  nnoremap <buffer> gs <Cmd>LspSymbolSearch<CR>
  nnoremap <buffer> yok <Cmd>LspInlayHints toggle<CR>
  nnoremap <buffer> ]k <Cmd>LspInlayHints enable<CR>
  nnoremap <buffer> [k <Cmd>LspInlayHints disable<CR>
  "setlocal omnifunc=ale#completion#OmniFunc
endfunction

" vim: foldmethod=marker
